package frontend

import (
	"embed"
	"io/fs"
)

// embeddedAssets contains the production frontend bundle generated by
// `npm --prefix frontend run build`.
//
//go:embed all:dist
var embeddedAssets embed.FS

// Assets exposes frontend/dist as the asset server root so Wails can resolve
// index.html and its referenced assets directly.
var Assets = mustSub(embeddedAssets, "dist")

func mustSub(assets fs.FS, dir string) fs.FS {
	sub, err := fs.Sub(assets, dir)
	if err != nil {
		panic(err)
	}
	return sub
}
