# NSIS runs before Vue. Keep every custom string translated in all nine languages.
# Standard buttons and page labels use NSIS translations. English is the fallback.
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "Korean"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "Spanish"
!insertmacro MUI_LANGUAGE "PortugueseBR"

# English
LangString DaygoWelcomeTitle ${LANG_ENGLISH} "Welcome to Daygo"
LangString DaygoWelcomeText ${LANG_ENGLISH} "Turn your activity into a timeline, daily summaries and weekly reviews.$\r$\n$\r$\nAfter installation, open Daygo to configure recording and your AI provider.$\r$\n$\r$\nIf WebView2 is missing, setup will download it from Microsoft. An internet connection is then required."
LangString DaygoDirectoryUser ${LANG_ENGLISH} "Install for your Windows account. Choose where to install Daygo."
LangString DaygoDirectoryMachine ${LANG_ENGLISH} "Install for all Windows accounts. Administrator permission is required."
LangString DaygoFinishTitle ${LANG_ENGLISH} "Daygo is ready"
LangString DaygoFinishText ${LANG_ENGLISH} "Open Daygo from the Start menu to get started.$\r$\n$\r$\nClosing the window leaves Daygo running in the notification area."
LangString DaygoLaunch ${LANG_ENGLISH} "Launch Daygo"
LangString DaygoDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString DaygoUninstallText ${LANG_ENGLISH} "Daygo will be removed. Your database, recordings, settings and saved credentials will be kept.$\r$\n$\r$\nExit Daygo from the notification area before continuing."
LangString DaygoUninstallTitle ${LANG_ENGLISH} "Daygo has been removed"
LangString DaygoUninstallFinish ${LANG_ENGLISH} "Your database, recordings, settings and saved credentials have been kept."
LangString DaygoWindowsRequired ${LANG_ENGLISH} "Daygo requires Windows 10 or later."
LangString DaygoArchitectureRequired ${LANG_ENGLISH} "This installer requires an amd64 (x64) Windows system."
LangString DaygoFilesBusy ${LANG_ENGLISH} "Daygo files are in use or cannot be changed. Exit Daygo from the notification area, check folder permissions, then run setup again."
LangString DaygoWebViewInstalling ${LANG_ENGLISH} "Installing WebView2. This may require an internet connection..."
LangString DaygoWebViewFailed ${LANG_ENGLISH} "WebView2 could not be installed. Check your internet connection or install Microsoft WebView2 Runtime, then run setup again. Daygo has not been installed or updated."
LangString DaygoInstalling ${LANG_ENGLISH} "Installing Daygo..."
LangString DaygoShortcutFailed ${LANG_ENGLISH} "The desktop shortcut could not be created. Open Daygo from the Start menu."
LangString DaygoLaunchFailed ${LANG_ENGLISH} "Daygo could not be started. Close setup and open Daygo from the Start menu."

# SimpChinese
LangString DaygoWelcomeTitle ${LANG_SIMPCHINESE} "欢迎安装 Daygo"
LangString DaygoWelcomeText ${LANG_SIMPCHINESE} "将活动整理为时间线、每日摘要和每周复盘。$\r$\n$\r$\n安装后打开 Daygo，配置录制和 AI 服务。$\r$\n$\r$\n如果缺少 WebView2，安装程序将从 Microsoft 下载，此时需要连接互联网。"
LangString DaygoDirectoryUser ${LANG_SIMPCHINESE} "仅为当前 Windows 账户安装。请选择 Daygo 的安装位置。"
LangString DaygoDirectoryMachine ${LANG_SIMPCHINESE} "为所有 Windows 账户安装，需要管理员权限。"
LangString DaygoFinishTitle ${LANG_SIMPCHINESE} "Daygo 安装完成"
LangString DaygoFinishText ${LANG_SIMPCHINESE} "从开始菜单打开 Daygo，即可开始配置。$\r$\n$\r$\n关闭窗口后，Daygo 仍会在通知区域运行。"
LangString DaygoLaunch ${LANG_SIMPCHINESE} "启动 Daygo"
LangString DaygoDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString DaygoUninstallText ${LANG_SIMPCHINESE} "将卸载 Daygo，保留数据库、录制、设置和已保存的凭据。$\r$\n$\r$\n继续前，请从通知区域退出 Daygo。"
LangString DaygoUninstallTitle ${LANG_SIMPCHINESE} "Daygo 已卸载"
LangString DaygoUninstallFinish ${LANG_SIMPCHINESE} "数据库、录制、设置和已保存的凭据已保留。"
LangString DaygoWindowsRequired ${LANG_SIMPCHINESE} "Daygo 需要 Windows 10 或更高版本。"
LangString DaygoArchitectureRequired ${LANG_SIMPCHINESE} "此安装程序需要 amd64（x64）Windows 系统。"
LangString DaygoFilesBusy ${LANG_SIMPCHINESE} "Daygo 文件正在使用或无法修改。请从通知区域退出 Daygo，检查文件夹权限后重新运行安装程序。"
LangString DaygoWebViewInstalling ${LANG_SIMPCHINESE} "正在安装 WebView2，可能需要连接互联网……"
LangString DaygoWebViewFailed ${LANG_SIMPCHINESE} "无法安装 WebView2。请检查网络连接，或安装 Microsoft WebView2 Runtime 后重试。Daygo 尚未安装或更新。"
LangString DaygoInstalling ${LANG_SIMPCHINESE} "正在安装 Daygo……"
LangString DaygoShortcutFailed ${LANG_SIMPCHINESE} "无法创建桌面快捷方式，请从开始菜单打开 Daygo。"
LangString DaygoLaunchFailed ${LANG_SIMPCHINESE} "无法启动 Daygo，请关闭安装程序后从开始菜单打开。"

# TradChinese
LangString DaygoWelcomeTitle ${LANG_TRADCHINESE} "歡迎安裝 Daygo"
LangString DaygoWelcomeText ${LANG_TRADCHINESE} "將活動整理為時間軸、每日摘要和每週回顧。$\r$\n$\r$\n安裝後開啟 Daygo，設定錄製和 AI 服務。$\r$\n$\r$\n若缺少 WebView2，安裝程式將從 Microsoft 下載，此時需要網際網路連線。"
LangString DaygoDirectoryUser ${LANG_TRADCHINESE} "僅為目前的 Windows 帳戶安裝。請選擇 Daygo 的安裝位置。"
LangString DaygoDirectoryMachine ${LANG_TRADCHINESE} "為所有 Windows 帳戶安裝，需要系統管理員權限。"
LangString DaygoFinishTitle ${LANG_TRADCHINESE} "Daygo 安裝完成"
LangString DaygoFinishText ${LANG_TRADCHINESE} "從開始功能表開啟 Daygo，即可開始設定。$\r$\n$\r$\n關閉視窗後，Daygo 仍會在通知區域執行。"
LangString DaygoLaunch ${LANG_TRADCHINESE} "啟動 Daygo"
LangString DaygoDesktop ${LANG_TRADCHINESE} "建立桌面捷徑"
LangString DaygoUninstallText ${LANG_TRADCHINESE} "將解除安裝 Daygo，保留資料庫、錄製、設定和已儲存的認證。$\r$\n$\r$\n繼續前，請從通知區域結束 Daygo。"
LangString DaygoUninstallTitle ${LANG_TRADCHINESE} "Daygo 已解除安裝"
LangString DaygoUninstallFinish ${LANG_TRADCHINESE} "資料庫、錄製、設定和已儲存的認證已保留。"
LangString DaygoWindowsRequired ${LANG_TRADCHINESE} "Daygo 需要 Windows 10 或更新版本。"
LangString DaygoArchitectureRequired ${LANG_TRADCHINESE} "此安裝程式需要 amd64（x64）Windows 系統。"
LangString DaygoFilesBusy ${LANG_TRADCHINESE} "Daygo 檔案正在使用或無法修改。請從通知區域結束 Daygo，檢查資料夾權限後重新執行安裝程式。"
LangString DaygoWebViewInstalling ${LANG_TRADCHINESE} "正在安裝 WebView2，可能需要網際網路連線……"
LangString DaygoWebViewFailed ${LANG_TRADCHINESE} "無法安裝 WebView2。請檢查網路連線，或安裝 Microsoft WebView2 Runtime 後重試。Daygo 尚未安裝或更新。"
LangString DaygoInstalling ${LANG_TRADCHINESE} "正在安裝 Daygo……"
LangString DaygoShortcutFailed ${LANG_TRADCHINESE} "無法建立桌面捷徑，請從開始功能表開啟 Daygo。"
LangString DaygoLaunchFailed ${LANG_TRADCHINESE} "無法啟動 Daygo，請關閉安裝程式後從開始功能表開啟。"

# Japanese
LangString DaygoWelcomeTitle ${LANG_JAPANESE} "Daygo へようこそ"
LangString DaygoWelcomeText ${LANG_JAPANESE} "アクティビティをタイムライン、日次サマリー、週次レビューにまとめます。$\r$\n$\r$\nインストール後、Daygo を開いて記録と AI サービスを設定してください。$\r$\n$\r$\nWebView2 がない場合は Microsoft からダウンロードするため、インターネット接続が必要です。"
LangString DaygoDirectoryUser ${LANG_JAPANESE} "現在の Windows アカウントにインストールします。保存先を選んでください。"
LangString DaygoDirectoryMachine ${LANG_JAPANESE} "すべての Windows アカウントにインストールします。管理者権限が必要です。"
LangString DaygoFinishTitle ${LANG_JAPANESE} "Daygo の準備ができました"
LangString DaygoFinishText ${LANG_JAPANESE} "スタートメニューから Daygo を開き、設定を始めてください。$\r$\n$\r$\nウィンドウを閉じても、Daygo は通知領域で動作を続けます。"
LangString DaygoLaunch ${LANG_JAPANESE} "Daygo を起動する"
LangString DaygoDesktop ${LANG_JAPANESE} "デスクトップにショートカットを作成する"
LangString DaygoUninstallText ${LANG_JAPANESE} "Daygo を削除します。データベース、記録、設定、保存済みの認証情報は残ります。$\r$\n$\r$\n続行する前に、通知領域から Daygo を終了してください。"
LangString DaygoUninstallTitle ${LANG_JAPANESE} "Daygo を削除しました"
LangString DaygoUninstallFinish ${LANG_JAPANESE} "データベース、記録、設定、保存済みの認証情報は保持されました。"
LangString DaygoWindowsRequired ${LANG_JAPANESE} "Daygo には Windows 10 以降が必要です。"
LangString DaygoArchitectureRequired ${LANG_JAPANESE} "このインストーラーには amd64（x64）の Windows が必要です。"
LangString DaygoFilesBusy ${LANG_JAPANESE} "Daygo のファイルが使用中か変更できません。通知領域から終了し、フォルダーの権限を確認してから再実行してください。"
LangString DaygoWebViewInstalling ${LANG_JAPANESE} "WebView2 をインストールしています。インターネット接続が必要な場合があります…"
LangString DaygoWebViewFailed ${LANG_JAPANESE} "WebView2 をインストールできませんでした。接続を確認するか、Microsoft WebView2 Runtime をインストールして再試行してください。Daygo はまだインストールまたは更新されていません。"
LangString DaygoInstalling ${LANG_JAPANESE} "Daygo をインストールしています…"
LangString DaygoShortcutFailed ${LANG_JAPANESE} "ショートカットを作成できませんでした。スタートメニューから Daygo を開いてください。"
LangString DaygoLaunchFailed ${LANG_JAPANESE} "Daygo を起動できませんでした。セットアップを閉じ、スタートメニューから開いてください。"

# Korean
LangString DaygoWelcomeTitle ${LANG_KOREAN} "Daygo 설치를 시작합니다"
LangString DaygoWelcomeText ${LANG_KOREAN} "활동을 타임라인, 일일 요약, 주간 리뷰로 정리합니다.$\r$\n$\r$\n설치 후 Daygo를 열어 기록과 AI 서비스를 설정하세요.$\r$\n$\r$\nWebView2가 없으면 Microsoft에서 다운로드하므로 인터넷 연결이 필요합니다."
LangString DaygoDirectoryUser ${LANG_KOREAN} "현재 Windows 계정에 설치합니다. Daygo 설치 위치를 선택하세요."
LangString DaygoDirectoryMachine ${LANG_KOREAN} "모든 Windows 계정에 설치합니다. 관리자 권한이 필요합니다."
LangString DaygoFinishTitle ${LANG_KOREAN} "Daygo 설치 완료"
LangString DaygoFinishText ${LANG_KOREAN} "시작 메뉴에서 Daygo를 열어 설정을 시작하세요.$\r$\n$\r$\n창을 닫아도 Daygo는 알림 영역에서 계속 실행됩니다."
LangString DaygoLaunch ${LANG_KOREAN} "Daygo 실행"
LangString DaygoDesktop ${LANG_KOREAN} "바탕 화면 바로 가기 만들기"
LangString DaygoUninstallText ${LANG_KOREAN} "Daygo를 제거합니다. 데이터베이스, 기록, 설정, 저장된 자격 증명은 유지됩니다.$\r$\n$\r$\n계속하기 전에 알림 영역에서 Daygo를 종료하세요."
LangString DaygoUninstallTitle ${LANG_KOREAN} "Daygo 제거 완료"
LangString DaygoUninstallFinish ${LANG_KOREAN} "데이터베이스, 기록, 설정, 저장된 자격 증명이 유지되었습니다."
LangString DaygoWindowsRequired ${LANG_KOREAN} "Daygo에는 Windows 10 이상이 필요합니다."
LangString DaygoArchitectureRequired ${LANG_KOREAN} "이 설치 프로그램에는 amd64(x64) Windows 시스템이 필요합니다."
LangString DaygoFilesBusy ${LANG_KOREAN} "Daygo 파일이 사용 중이거나 변경할 수 없습니다. 알림 영역에서 종료하고 폴더 권한을 확인한 후 설치를 다시 실행하세요."
LangString DaygoWebViewInstalling ${LANG_KOREAN} "WebView2를 설치하고 있습니다. 인터넷 연결이 필요할 수 있습니다…"
LangString DaygoWebViewFailed ${LANG_KOREAN} "WebView2를 설치할 수 없습니다. 인터넷 연결을 확인하거나 Microsoft WebView2 Runtime을 설치한 후 다시 시도하세요. Daygo는 아직 설치 또는 업데이트되지 않았습니다."
LangString DaygoInstalling ${LANG_KOREAN} "Daygo를 설치하고 있습니다…"
LangString DaygoShortcutFailed ${LANG_KOREAN} "바로 가기를 만들 수 없습니다. 시작 메뉴에서 Daygo를 여세요."
LangString DaygoLaunchFailed ${LANG_KOREAN} "Daygo를 실행할 수 없습니다. 설치 프로그램을 닫고 시작 메뉴에서 여세요."

# German
LangString DaygoWelcomeTitle ${LANG_GERMAN} "Willkommen bei Daygo"
LangString DaygoWelcomeText ${LANG_GERMAN} "Aktivitäten als Zeitleiste, Tagesberichte und Wochenrückblicke.$\r$\n$\r$\nÖffnen Sie danach Daygo, um Aufzeichnung und KI-Dienst einzurichten.$\r$\n$\r$\nFehlt WebView2, wird es von Microsoft geladen. Dafür ist eine Internetverbindung nötig."
LangString DaygoDirectoryUser ${LANG_GERMAN} "Installation für Ihr Windows-Konto. Wählen Sie den Zielordner."
LangString DaygoDirectoryMachine ${LANG_GERMAN} "Installation für alle Windows-Konten. Administratorrechte sind erforderlich."
LangString DaygoFinishTitle ${LANG_GERMAN} "Daygo ist bereit"
LangString DaygoFinishText ${LANG_GERMAN} "Öffnen Sie Daygo im Startmenü, um die Einrichtung zu beginnen.$\r$\n$\r$\nNach dem Schließen des Fensters läuft Daygo im Infobereich weiter."
LangString DaygoLaunch ${LANG_GERMAN} "Daygo starten"
LangString DaygoDesktop ${LANG_GERMAN} "Desktop-Verknüpfung erstellen"
LangString DaygoUninstallText ${LANG_GERMAN} "Daygo wird entfernt. Datenbank, Aufzeichnungen, Einstellungen und gespeicherte Zugangsdaten bleiben erhalten.$\r$\n$\r$\nBeenden Sie Daygo zuvor im Infobereich."
LangString DaygoUninstallTitle ${LANG_GERMAN} "Daygo wurde entfernt"
LangString DaygoUninstallFinish ${LANG_GERMAN} "Datenbank, Aufzeichnungen, Einstellungen und Zugangsdaten bleiben erhalten."
LangString DaygoWindowsRequired ${LANG_GERMAN} "Daygo benötigt Windows 10 oder neuer."
LangString DaygoArchitectureRequired ${LANG_GERMAN} "Dieses Installationsprogramm benötigt Windows für amd64 (x64)."
LangString DaygoFilesBusy ${LANG_GERMAN} "Daygo-Dateien werden verwendet oder lassen sich nicht ändern. Beenden Sie Daygo im Infobereich, prüfen Sie die Ordnerrechte und starten Sie die Installation erneut."
LangString DaygoWebViewInstalling ${LANG_GERMAN} "WebView2 wird installiert. Eine Internetverbindung kann erforderlich sein…"
LangString DaygoWebViewFailed ${LANG_GERMAN} "WebView2 konnte nicht installiert werden. Prüfen Sie die Internetverbindung oder installieren Sie Microsoft WebView2 Runtime und versuchen Sie es erneut. Daygo wurde nicht installiert oder aktualisiert."
LangString DaygoInstalling ${LANG_GERMAN} "Daygo wird installiert…"
LangString DaygoShortcutFailed ${LANG_GERMAN} "Die Desktop-Verknüpfung konnte nicht erstellt werden. Öffnen Sie Daygo im Startmenü."
LangString DaygoLaunchFailed ${LANG_GERMAN} "Daygo konnte nicht gestartet werden. Schließen Sie die Installation und öffnen Sie Daygo im Startmenü."

# French
LangString DaygoWelcomeTitle ${LANG_FRENCH} "Bienvenue dans Daygo"
LangString DaygoWelcomeText ${LANG_FRENCH} "Vos activités en chronologie, résumés quotidiens et bilans hebdomadaires.$\r$\n$\r$\nOuvrez ensuite Daygo pour configurer la capture et le service IA.$\r$\n$\r$\nSi WebView2 manque, il sera téléchargé depuis Microsoft. Une connexion Internet sera alors nécessaire."
LangString DaygoDirectoryUser ${LANG_FRENCH} "Installation pour votre compte Windows. Choisissez le dossier."
LangString DaygoDirectoryMachine ${LANG_FRENCH} "Installation pour tous les comptes Windows. Droits administrateur requis."
LangString DaygoFinishTitle ${LANG_FRENCH} "Daygo est prêt"
LangString DaygoFinishText ${LANG_FRENCH} "Ouvrez Daygo dans le menu Démarrer pour le configurer.$\r$\n$\r$\nAprès fermeture de la fenêtre, Daygo reste actif dans la zone de notification."
LangString DaygoLaunch ${LANG_FRENCH} "Lancer Daygo"
LangString DaygoDesktop ${LANG_FRENCH} "Créer un raccourci sur le bureau"
LangString DaygoUninstallText ${LANG_FRENCH} "Daygo sera supprimé. La base de données, les captures, les paramètres et les identifiants enregistrés seront conservés.$\r$\n$\r$\nQuittez Daygo depuis la zone de notification avant de continuer."
LangString DaygoUninstallTitle ${LANG_FRENCH} "Daygo a été supprimé"
LangString DaygoUninstallFinish ${LANG_FRENCH} "La base de données, les captures, les paramètres et les identifiants ont été conservés."
LangString DaygoWindowsRequired ${LANG_FRENCH} "Daygo nécessite Windows 10 ou une version ultérieure."
LangString DaygoArchitectureRequired ${LANG_FRENCH} "Cet installateur nécessite un système Windows amd64 (x64)."
LangString DaygoFilesBusy ${LANG_FRENCH} "Les fichiers Daygo sont utilisés ou ne peuvent pas être modifiés. Quittez Daygo depuis la zone de notification, vérifiez les droits du dossier et relancez l’installation."
LangString DaygoWebViewInstalling ${LANG_FRENCH} "Installation de WebView2. Une connexion Internet peut être nécessaire…"
LangString DaygoWebViewFailed ${LANG_FRENCH} "Impossible d’installer WebView2. Vérifiez la connexion Internet ou installez Microsoft WebView2 Runtime, puis réessayez. Daygo n’a pas été installé ni mis à jour."
LangString DaygoInstalling ${LANG_FRENCH} "Installation de Daygo…"
LangString DaygoShortcutFailed ${LANG_FRENCH} "Impossible de créer le raccourci. Ouvrez Daygo dans le menu Démarrer."
LangString DaygoLaunchFailed ${LANG_FRENCH} "Impossible de lancer Daygo. Fermez l’installateur et ouvrez Daygo dans le menu Démarrer."

# Spanish
LangString DaygoWelcomeTitle ${LANG_SPANISH} "Bienvenido a Daygo"
LangString DaygoWelcomeText ${LANG_SPANISH} "Tu actividad como cronología, resúmenes diarios y revisiones semanales.$\r$\n$\r$\nDespués, abre Daygo para configurar la captura y el servicio de IA.$\r$\n$\r$\nSi falta WebView2, se descargará desde Microsoft. En ese caso se necesita conexión a Internet."
LangString DaygoDirectoryUser ${LANG_SPANISH} "Instalación para tu cuenta de Windows. Elige la carpeta de destino."
LangString DaygoDirectoryMachine ${LANG_SPANISH} "Instalación para todas las cuentas de Windows. Requiere permisos de administrador."
LangString DaygoFinishTitle ${LANG_SPANISH} "Daygo está listo"
LangString DaygoFinishText ${LANG_SPANISH} "Abre Daygo desde el menú Inicio para configurarlo.$\r$\n$\r$\nAl cerrar la ventana, Daygo sigue activo en el área de notificación."
LangString DaygoLaunch ${LANG_SPANISH} "Iniciar Daygo"
LangString DaygoDesktop ${LANG_SPANISH} "Crear un acceso directo en el escritorio"
LangString DaygoUninstallText ${LANG_SPANISH} "Se eliminará Daygo. Se conservarán la base de datos, las capturas, los ajustes y las credenciales guardadas.$\r$\n$\r$\nAntes de continuar, cierra Daygo desde el área de notificación."
LangString DaygoUninstallTitle ${LANG_SPANISH} "Daygo se ha eliminado"
LangString DaygoUninstallFinish ${LANG_SPANISH} "Se han conservado la base de datos, las capturas, los ajustes y las credenciales."
LangString DaygoWindowsRequired ${LANG_SPANISH} "Daygo requiere Windows 10 o posterior."
LangString DaygoArchitectureRequired ${LANG_SPANISH} "Este instalador requiere Windows amd64 (x64)."
LangString DaygoFilesBusy ${LANG_SPANISH} "Los archivos de Daygo están en uso o no se pueden modificar. Cierra Daygo desde el área de notificación, revisa los permisos de la carpeta y repite la instalación."
LangString DaygoWebViewInstalling ${LANG_SPANISH} "Instalando WebView2. Puede requerir conexión a Internet…"
LangString DaygoWebViewFailed ${LANG_SPANISH} "No se pudo instalar WebView2. Comprueba la conexión a Internet o instala Microsoft WebView2 Runtime y vuelve a intentarlo. Daygo no se ha instalado ni actualizado."
LangString DaygoInstalling ${LANG_SPANISH} "Instalando Daygo…"
LangString DaygoShortcutFailed ${LANG_SPANISH} "No se pudo crear el acceso directo. Abre Daygo desde el menú Inicio."
LangString DaygoLaunchFailed ${LANG_SPANISH} "No se pudo iniciar Daygo. Cierra el instalador y abre Daygo desde el menú Inicio."

# PortugueseBR
LangString DaygoWelcomeTitle ${LANG_PORTUGUESEBR} "Bem-vindo ao Daygo"
LangString DaygoWelcomeText ${LANG_PORTUGUESEBR} "Suas atividades em uma linha do tempo, resumos diários e revisões semanais.$\r$\n$\r$\nDepois, abra o Daygo para configurar a captura e o serviço de IA.$\r$\n$\r$\nSe faltar o WebView2, ele será baixado da Microsoft. Nesse caso, será necessária uma conexão com a Internet."
LangString DaygoDirectoryUser ${LANG_PORTUGUESEBR} "Instalação para sua conta do Windows. Escolha a pasta de destino."
LangString DaygoDirectoryMachine ${LANG_PORTUGUESEBR} "Instalação para todas as contas do Windows. Requer permissão de administrador."
LangString DaygoFinishTitle ${LANG_PORTUGUESEBR} "O Daygo está pronto"
LangString DaygoFinishText ${LANG_PORTUGUESEBR} "Abra o Daygo pelo menu Iniciar para começar a configuração.$\r$\n$\r$\nAo fechar a janela, o Daygo continua ativo na área de notificação."
LangString DaygoLaunch ${LANG_PORTUGUESEBR} "Iniciar o Daygo"
LangString DaygoDesktop ${LANG_PORTUGUESEBR} "Criar um atalho na área de trabalho"
LangString DaygoUninstallText ${LANG_PORTUGUESEBR} "O Daygo será removido. O banco de dados, as capturas, as configurações e as credenciais salvas serão mantidos.$\r$\n$\r$\nAntes de continuar, encerre o Daygo pela área de notificação."
LangString DaygoUninstallTitle ${LANG_PORTUGUESEBR} "O Daygo foi removido"
LangString DaygoUninstallFinish ${LANG_PORTUGUESEBR} "O banco de dados, as capturas, as configurações e as credenciais foram mantidos."
LangString DaygoWindowsRequired ${LANG_PORTUGUESEBR} "O Daygo requer Windows 10 ou posterior."
LangString DaygoArchitectureRequired ${LANG_PORTUGUESEBR} "Este instalador requer um sistema Windows amd64 (x64)."
LangString DaygoFilesBusy ${LANG_PORTUGUESEBR} "Os arquivos do Daygo estão em uso ou não podem ser alterados. Encerre o Daygo pela área de notificação, confira as permissões da pasta e execute a instalação novamente."
LangString DaygoWebViewInstalling ${LANG_PORTUGUESEBR} "Instalando o WebView2. Pode ser necessária uma conexão com a Internet…"
LangString DaygoWebViewFailed ${LANG_PORTUGUESEBR} "Não foi possível instalar o WebView2. Confira a conexão ou instale o Microsoft WebView2 Runtime e tente novamente. O Daygo não foi instalado nem atualizado."
LangString DaygoInstalling ${LANG_PORTUGUESEBR} "Instalando o Daygo…"
LangString DaygoShortcutFailed ${LANG_PORTUGUESEBR} "Não foi possível criar o atalho. Abra o Daygo pelo menu Iniciar."
LangString DaygoLaunchFailed ${LANG_PORTUGUESEBR} "Não foi possível iniciar o Daygo. Feche o instalador e abra o Daygo pelo menu Iniciar."
